source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RTIconButton_Example' do
  pod "RTIconButton", :path => "../"
end

target 'RTIconButton_Tests' do
  pod "RTIconButton", :path => "../"
end
